# Alex' Monokai Color Scheme: AX-Monokai
# 2024-11-08, alex@barton.de
#
# AX-Monokai master configuration file.
# Infos in braces denote where those settings are coming from.
#
# These settings are directly useable for the Kitty terminal emulator
# configuration file `kitty.conf`.
#

background_opacity 0.95

# (Monokai Pro Classic)
background #272822
foreground #c2c2bf

# (Alex)
cursor #ff5820
cursor_text_color #f5f4f1

# (Alex)
selection_background #0A5D78
selection_foreground #f5f4f1

# Black (Monokai Pro Classic)
color0 #1e1f1c
# Bright black (+33%)
color8 #6a6d63
# Red (Monokai Pro Classic + Base16 Monokai)
color1 #f92672
# Bright red (+33%)
color9 #fb6ea1
# Green (Monokai Pro Classic + Base16 Monokai)
color2 #a6e22e
# Bright green (+33%)
color10 #c3ec73
# Yellow (Base16 Monokai)
color3 #fd971f
# Bright yellow (+33%)
color11 #feb969
# Blue (Alex)
color4 #2c64e0
# Bright blue (+33%)
color12 #7297ea
# Magenta (Alex)
color5 #f94cff
# Bright magenta (+33%)
color13 #fb87ff
# Cyan (-33%)
color6 #16b1cf
# Bright cyan (Monokai Pro Classic + Base16 Monokai)
color14 #66d9ef
# White (Monokai Pro Classic)
color7 #c2c2bf
# Bright white (Base16 Monokai)
color15 #f5f4f1
